name: KotlinTemplate-OG
author: Sekalol15
description: Kotlin plugin template for the OG Suite
website: https://github.com/Sekalol15/KotlinTemplate-OG
version: '${version}'
api-version: '${apiVersion}' 
main: plugin.KotlinTemplateOG
